// <auto-generated />
using System;
using Archangel.Tests.WebEditor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Archangel.Tests.WebEditor.Data.Migrations
{
    [DbContext(typeof(WebEditorDbContext))]
    [Migration("20190414140317_Added_update_on_field_to_news")]
    partial class Added_update_on_field_to_news
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Archangel.Tests.WebEditor.Data.Domains.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Text")
                        .IsRequired();

                    b.Property<DateTime?>("UpdateOn");

                    b.HasKey("NewsId");

                    b.ToTable("News");

                    b.HasDiscriminator<string>("Discriminator").HasValue("News");
                });

            modelBuilder.Entity("Archangel.Tests.WebEditor.Data.Domains.ActiveNews", b =>
                {
                    b.HasBaseType("Archangel.Tests.WebEditor.Data.Domains.News");

                    b.HasDiscriminator().HasValue("ActiveNews");
                });

            modelBuilder.Entity("Archangel.Tests.WebEditor.Data.Domains.ArchivedNews", b =>
                {
                    b.HasBaseType("Archangel.Tests.WebEditor.Data.Domains.News");

                    b.Property<DateTime>("ArchivedOn");

                    b.HasDiscriminator().HasValue("ArchivedNews");
                });

            modelBuilder.Entity("Archangel.Tests.WebEditor.Data.Domains.DraftNews", b =>
                {
                    b.HasBaseType("Archangel.Tests.WebEditor.Data.Domains.News");

                    b.HasDiscriminator().HasValue("DraftNews");
                });
#pragma warning restore 612, 618
        }
    }
}
